name: Deploy to production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup node and install dependencies
        uses: actions/setup-node@v2
        with:
          node-version: '20.17.0'

      - name: Build docker image
        run: |
          docker build -t codium-backend --target production .
      - name: Delete old container
        run: docker rm -f codium-backend
      - name: Run docker container
        run: docker run -d -p 3000:3000 --restart always --name codium-backend codium-backend
