name: Deploy to production

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Docker image build

    steps:
      - uses: actions/checkout@v4
      - name: Setup node and install dependencies
        uses: actions/setup-node@v4
        with:
          node-version: '20.17.0'
      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/codium-backend \
                      --build-arg JWT_SECRET=${{ secrets.JWT_SECRET }} \
                      --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} \
                      --target=production .
      - name: Push docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/codium-backend:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    name: Deployment
    steps:
      - name: Deploy using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd codium-backend;
            git pull;
            docker stop codium-backend;
            docker rm codium-backend;
            docker pull akmatoff/codium-backend:latest;
            docker run --restart always -d -p 3000:3000 --name codium-backend akmatoff/codium-backend:latest;
